// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikdqbiumciskarxwooln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZHFiaXVtY2lza2FyeHdvb2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTYxOTQsImV4cCI6MjA2NTQ3MjE5NH0.eBkhp-3p0Vw6Dzp5VUoF5aUxJ4OpmG02TyCKDWj1p9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);